# Generated by Django 3.2.8 on 2021-10-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Course_Number', models.IntegerField()),
                ('Instructor_Name', models.CharField(max_length=25)),
                ('Duration', models.FloatField()),
            ],
        ),
    ]
